name: Linting, Formatting and Unit and Integration Tests
on:
  push:
jobs:
  verify-code-integrity-and-run-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout/@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: npm
      - name: Install dependencies
        run: npm i
      - name: Run Prettier
        run: npm run format
      - name: Run Linting Checks
        run: npm run lint
      - name: Build Application
        run: npm run build
      - name: Run Unit and Integration Tests
        run: npm run test a
